#!/usr/bin/env python3
"""Generate a static package index page for the bucket.

Reads bucket/*.json and writes docs/_site/index.html.
Stdlib only; output is deterministic (sorted by package name).
"""

import html
import json
from pathlib import Path

REPO = "danalec/scoop-alts"
REPO_NAME = "scoop-alts"
DESCRIPTION = (
    "Curated Windows software manifests with enhanced packaging, "
    "automated quality assurance, and intelligent lifecycle management."
)

ROOT = Path(__file__).resolve().parent.parent
BUCKET_DIR = ROOT / "bucket"
OUT_DIR = ROOT / "docs" / "_site"
OUT_FILE = OUT_DIR / "index.html"


def load_manifests():
    packages = []
    for path in sorted(BUCKET_DIR.glob("*.json")):
        with path.open(encoding="utf-8") as f:
            manifest = json.load(f)
        persist = manifest.get("persist", "")
        if isinstance(persist, list):
            persist = ", ".join(str(p) for p in persist)
        packages.append(
            {
                "name": path.stem,
                "version": str(manifest.get("version", "")),
                "description": str(manifest.get("description", "")),
                "homepage": str(manifest.get("homepage", "")),
                "persist": str(persist),
            }
        )
    return packages


def render(packages):
    rows = []
    for pkg in packages:
        manifest_url = f"https://github.com/{REPO}/blob/master/bucket/{pkg['name']}.json"
        if pkg["homepage"]:
            homepage = (
                f'<a href="{html.escape(pkg["homepage"], quote=True)}">'
                f"{html.escape(pkg['homepage'])}</a>"
            )
        else:
            homepage = ""
        persist = html.escape(pkg["persist"]) if pkg["persist"] else "&mdash;"
        rows.append(
            "<tr>"
            f'<td><a href="{manifest_url}"><code>{html.escape(pkg["name"])}</code></a></td>'
            f"<td>{html.escape(pkg['version'])}</td>"
            f"<td>{html.escape(pkg['description'])}</td>"
            f"<td>{homepage}</td>"
            f"<td>{persist}</td>"
            "</tr>"
        )

    return "\n".join(
        [
            "<!DOCTYPE html>",
            '<html lang="en">',
            "<head>",
            '  <meta charset="utf-8">',
            '  <meta name="viewport" content="width=device-width, initial-scale=1">',
            f"  <title>{REPO_NAME} - Scoop Bucket</title>",
            "</head>",
            "<body>",
            f"  <header><h1>{REPO_NAME}</h1><p>{html.escape(DESCRIPTION)}</p></header>",
            "  <main>",
            f"  <p>{len(packages)} packages</p>",
            "  <table>",
            "    <thead><tr><th>Package</th><th>Version</th>"
            "<th>Description</th><th>Homepage</th><th>Persist</th></tr></thead>",
            "    <tbody>",
            *[f"      {row}" for row in rows],
            "    </tbody>",
            "  </table>",
            "  </main>",
            "  <footer>generated by generate-site.py - do not edit</footer>",
            "</body>",
            "</html>",
            "",
        ]
    )


def main():
    packages = load_manifests()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(render(packages), encoding="utf-8")
    print(f"Wrote {OUT_FILE} with {len(packages)} package rows")


if __name__ == "__main__":
    main()
